/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

use std::io;

fn main() {
    println!("This programming aiming to find the sum of the even-valued terms in fibonacci sequence!");
    let _sequence_length: String = String::new();

    println!("Enter the legnth of fibonacci sequence that you want");
    
    //readline
    io::stdin().read_line(&mut _sequence_length)
    .expect(r#"FAILED to READ LINE!"#);
}


fn find_even_valued_terms(){

}
